Feature/page for instruction
yahorbukhta/alephium-pool pull request #11
Opened 2024-02-21 21:20 UTC by AndrewMatsiash

2024-02-22 11:12 UTC, nnslvp requested changes

2024-02-22 11:12 UTC, nnslvp commented on index.html
Для чего все эти изменения?

2024-02-22 11:12 UTC, nnslvp commented on instruction.html
> +    *,
Стили должны быть в файле

2024-02-22 11:12 UTC, nnslvp commented on instruction.html
> +    *,
Почему не юзаешь milligram.css ?

2024-02-22 12:55 UTC, AndrewMatsiash commented on index.html
это мой автоформатер  маркдоун отформатировал,уберу измениния,хотя на отображение они ни как не влияют

2024-02-22 12:56 UTC, AndrewMatsiash commented on instruction.html
> +    *,
стили перенесу в файл,а по поводу milligram.css, я что то не обратил внимание, что ты его использовал,сейчас посмотрю,что это за либа и использую ее

2024-02-22 13:28 UTC, nnslvp commented on instruction.html
> +    *,
Давай по максимуму использовать milligram.css чтоб все было в одном стиле

2024-02-22 16:02 UTC, nnslvp commented on styles.css
> +	display: flex;
Меняй только то что касается задачи

2024-02-22 16:04 UTC, nnslvp commented on instruction.html
> +        <h2>Alephium mining pool</h2>
```suggestion
        <h2>Instruction</h2>
```

Сделай плз SEO френдли разметку, то есть h1 один на страницу и другие заголовки h2 и так далее

2024-02-22 16:09 UTC, nnslvp commented on guide.html
> +          <h1>Quick Start</h1>
Мне кажется это не очень хороший текст для h1, давай сделаем сео френдли разметку

2024-02-22 16:10 UTC, nnslvp reviewed
Не забудь обновить ссылку на инструкцию на главное странице

2024-02-22 16:11 UTC, nnslvp commented on README.md
> -* Region auto detection: **detect-my-region.alephium-pool.com:20032**
Не меняй ничего лишнего

2024-02-22 16:30 UTC, AndrewMatsiash commented on README.md
> -* Region auto detection: **detect-my-region.alephium-pool.com:20032**
ссылку  на главную добавил,файл readme взял из master и вставил,чтобы он был как изначальный,h1 добавил

2024-02-22 16:38 UTC, nnslvp commented on index.html
> -    <!-- Google Tag Manager -->
Не делай лишних изменений

2024-02-22 16:39 UTC, nnslvp commented on instruction.html
> +          <h3 class="profit">💵 Fee: 0.5%</h3>
Это можно убрать

2024-02-22 16:40 UTC, nnslvp commented on instruction.html
> +        <h2>Alephium mining pool</h2>
Instruction

2024-02-22 16:42 UTC, AndrewMatsiash commented on instruction.html
> +          <h3 class="profit">💵 Fee: 0.5%</h3>
не совсем понял, что убрать  Site ?

2024-02-22 17:08 UTC, nnslvp commented on instruction.html
> +          <h3 class="profit">💵 Fee: 0.5%</h3>
Я указал 23 строку, там fee

2024-02-23 08:16 UTC, AndrewMatsiash commented on instruction.html
> +          <h3 class="profit">💵 Fee: 0.5%</h3>
убрал

2024-02-23 08:16 UTC, AndrewMatsiash commented on instruction.html
> +          <h3 class="profit">💵 Fee: 0.5%</h3>
мне просто показывает с 20 по 23

2024-02-23 08:18 UTC, AndrewMatsiash commented on instruction.html
> +        <h2>Alephium mining pool</h2>
сделал

2024-02-23 12:26 UTC, AndrewMatsiash commented on styles.css
> +	display: flex;
ничего не менял,это у меня стоит авто форматер и он если заходишь в файл и меняшь фокус форматирует,нужно я так понимаю его отключать и форматировать в ручную,только там где нужно

2024-02-23 12:27 UTC, AndrewMatsiash commented on guide.html
> +          <h1>Quick Start</h1>
это исправил

2024-02-23 12:27 UTC, AndrewMatsiash commented on index.html
> -    <!-- Google Tag Manager -->
тут таже тема с форматированием,а там ничего не менял в плане кода

2024-02-23 12:27 UTC, AndrewMatsiash commented on instruction.html
> +        <h2>Alephium mining pool</h2>
исправил

2024-02-23 12:57 UTC, nnslvp commented on index.html
> -    <!-- Google Tag Manager -->
@AndrewMatsiash Убери все лишние изменения

2024-02-23 12:58 UTC, nnslvp commented on styles.css
> +	display: flex;
@AndrewMatsiash Убери все лишние изменения

2024-02-23 13:34 UTC, AndrewMatsiash commented on index.html
> -    <!-- Google Tag Manager -->
сделал, вернул исходные файлы из мастера с родным форматированием

2024-02-23 14:14 UTC, nnslvp approved these changes

2024-02-23 14:17 UTC, merged