Feature/new feature rendering and receiving list ping servers
yahorbukhta/alephium-pool pull request #19
Opened 2024-02-28 13:16 UTC by AndrewMatsiash

2024-02-28 13:28 UTC, nnslvp requested changes

2024-02-28 13:28 UTC, nnslvp commented on index.html
> +        <table class="table-servers">
<img width="2715" alt="image" src="https://github.com/nnslvp/alephium-pool/assets/65916399/37dbcfa8-30de-4552-8201-92eb511216a5">
1. Выглядит так себе, нужно либо сделать таблицу уже либо не использовать таблицу вовсе, не забудь про адаптив

3. Значения отображаются одновременно, отображай по мере добавления значений, сверху вниз

5. Никак не помечается самый быстрый сервер

2024-02-28 13:28 UTC, nnslvp commented on index.html
> +            <th>Ping</th> <!-- Добавляем столбец для пинга, если нужно -->
Не забудь удалить комментарии

2024-02-28 13:28 UTC, nnslvp commented on instruction.js
> +	const id = `ping-${server.name.replaceAll(' ', '')}`
Давай обойдемся без server.name.replaceAll, ты можешь поменять имя в объекте

2024-02-28 13:28 UTC, nnslvp commented on instruction.js
> +			console.log(`${server.name} не смог установить соединение`)
Не нужно писать это в консоль

2024-02-28 13:28 UTC, nnslvp commented on instruction.js
> +			console.error('Ошибка копирования: ', err)
не нужно

2024-02-28 15:58 UTC, AndrewMatsiash commented on index.html
> +        <table class="table-servers">
сделал уже таблицу,выделил сервер самый быстрый,добавляются по сверху в низ плавно.

2024-02-28 15:58 UTC, AndrewMatsiash commented on index.html
> +            <th>Ping</th> <!-- Добавляем столбец для пинга, если нужно -->
удалил

2024-02-28 15:58 UTC, AndrewMatsiash commented on instruction.js
> +	const id = `ping-${server.name.replaceAll(' ', '')}`
убрал

2024-02-28 15:58 UTC, AndrewMatsiash commented on instruction.js
> +			console.log(`${server.name} не смог установить соединение`)
убрал

2024-02-28 15:58 UTC, AndrewMatsiash commented on instruction.js
> +			console.error('Ошибка копирования: ', err)
убрал

2024-02-28 16:23 UTC, nnslvp requested changes

2024-02-28 16:23 UTC, nnslvp commented on instruction.html
> +              <table class="table-servers">
предлагаю добавить пинг только на главную

2024-02-28 16:23 UTC, nnslvp commented on index.html
> +            <th>Ping</th>
Добавь плз вопросик, или что-то в этом вроде чтоб было понятно что у этого заголовка есть тултип, и добавь тултип с таким содержимым: "This ping is approximate but accurate enough for comparing servers with each other. For obtaining the exact ping, use the ping command in your system."

2024-02-29 12:45 UTC, AndrewMatsiash commented on instruction.html
> +              <table class="table-servers">
сделал

2024-02-29 12:45 UTC, AndrewMatsiash commented on index.html
> +            <th>Ping</th>
сделал

2024-02-29 13:16 UTC, nnslvp requested changes

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +    name: 'Region auto detection',
```suggestion
    name: 'RegionAutoDetection',
```

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +					server.name === 'Region auto detection'
Для чего это условие?

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +      resolve()
Выглядит странно, тут точно нужен промис?

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +      updatePing(nameServer, timeTaken)
Если юзать промис то по идее эта штука должна быть в then?

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +    const startTime = new Date().getTime()
Помести эту строку ниже, нужно минимизировать операции между startTime и timeTaken

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +  for (let index = 0; index < servers.length; index++) {
почеум не foreach ?

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +    await new Promise(resolve => setTimeout(resolve, 500))
Не мешай async-await и коллбеки, либо то либо то

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +	const id = `ping-${serverName}`
Можно обойтись без этой переменной

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +
Лишняя пустая строка

2024-02-29 13:16 UTC, nnslvp commented on main.js
> +	await testServers(servers)
почему не коллбеки или промисы?

2024-02-29 13:16 UTC, nnslvp commented on index.html
> +
?

2024-02-29 13:16 UTC, nnslvp commented on index.html
> +        <table  class="table-servers">
```suggestion
        <table class="table-servers">
```

2024-02-29 17:12 UTC, nnslvp requested changes
Код нужно форматировать по примеру уже имеющегося кода

2024-02-29 17:12 UTC, nnslvp commented on main.js
> +function testServers(servers) {
Код странно форматирован

2024-02-29 17:12 UTC, nnslvp commented on main.js
> +	if (!serverName || !pingValue) {
странные табуляции

2024-02-29 17:12 UTC, nnslvp commented on instruction.js
> +	btn.addEventListener('click', event => {
Табуляции

2024-02-29 17:12 UTC, nnslvp commented on instruction.js
> +})
EOF

2024-02-29 17:12 UTC, nnslvp commented on main.js
> +
Для чего это?

2024-02-29 17:12 UTC, nnslvp commented on styles.css
> +	font-size: 0.625rem;
табуляции разные

2024-03-01 11:11 UTC, nnslvp requested changes

2024-03-01 11:11 UTC, nnslvp commented on main.js
> +testServers(servers);
Думаю это можно поместить в init

2024-03-01 11:11 UTC, nnslvp commented on main.js
> +testServers(servers);
```suggestion
showPings(servers);
```

2024-03-01 11:11 UTC, nnslvp commented on main.js
> +const serversPing = [];
почему не let?

2024-03-01 11:11 UTC, nnslvp commented on main.js
> +const serversPing = [];
Мне кажется мы можем упростить код и избавится от пременной-состояния, или мне кажется?

2024-03-01 11:11 UTC, nnslvp commented on main.js
> +  const fasterServer = getFasterServer(serversPing);
Я бы не разбивал этот код на функции, если все собрать в один получится не большая и понятная функция

2024-03-01 11:11 UTC, nnslvp commented on main.js
> +      renderAndStyleServerFaster();
мб мы можем обьявить const serversPing = []; внутри testServers и потом сделать renderAndStyleServerFaster(serversPing); верно?

2024-03-01 14:47 UTC, nnslvp commented on main.js
> +const servers = [
по идее ты можешь объявить это прямо в showPings

2024-03-02 12:39 UTC, merged