feat: hash rate measures
yahorbukhta/alephium-pool pull request #3
Opened 2022-12-07 20:24 UTC by vadimzhukov

2022-12-08 14:52 UTC, yahorbukhta requested changes

2022-12-08 14:52 UTC, yahorbukhta commented on stats.js
> +        const factor = (hashRateFactor / 12) >= 1 ? denominator['12'] :
Разверни пожалуйста в не сокращенную форму if-else

2022-12-08 17:04 UTC, vadimzhukov commented on stats.js
> +        const factor = (hashRateFactor / 12) >= 1 ? denominator['12'] :
fixed

2022-12-08 17:09 UTC, yahorbukhta requested changes

2022-12-08 17:09 UTC, yahorbukhta commented on stats.js
> +        }
Я бы слегка изменил структуру denominator для того чтобы можно было сделать так:

const factor  = denominator.find(d=> hashRateFactor / 12  >= d.decimals)

2022-12-08 19:14 UTC, yahorbukhta requested changes

2022-12-08 19:14 UTC, nnslvp commented on stats.js
> +        [1000000000, 'GH'],
здесь нет причин использовать массив массивов вместо массива объектов

2022-12-08 19:14 UTC, nnslvp commented on stats.js
> +            'hashrate': resultHashRateValue,
кавычки не нужны

2022-12-08 19:14 UTC, nnslvp commented on stats.js
> +        const factor = denominator.find(el => hashRateFactor - Math.log10(el[0]) >= 0)
выглядит так как будто не обработан кейс с очень большим числом

2022-12-08 19:14 UTC, yahorbukhta commented
конфликты

2022-12-08 19:31 UTC, vadimzhukov commented on stats.js
> +        const factor = denominator.find(el => hashRateFactor - Math.log10(el[0]) >= 0)
20 знаков тестировал, работает

2022-12-08 22:05 UTC, yahorbukhta commented on stats.js
> +        const factor = denominator.find(el => hashRateFactor - Math.log10(el[0]) >= 0)
и изменяется в T? что на счет 30,40,50 знаков? должно так же в Т, судя по коду оно не найдет подходящий деноменатор, или не так?

2022-12-08 23:59 UTC, vadimzhukov commented on stats.js
> +        const factor = denominator.find(el => hashRateFactor - Math.log10(el[0]) >= 0)
В Т тоже изменяется. Все будет ок :) я же вычисляю log10 от переданного значения hashrate и получаю по сути разрядность числа (или 0 если разрядность отрицательная, т.е. < 1) и далее вычитаю из этой разрядности разрядность деноминатора (12 или 9 или 6 или 0) и проверяю разность на >= 0.

2022-12-09 13:25 UTC, nnslvp commented
Функционал так же надо применить на главной странице

2022-12-09 13:25 UTC, nnslvp commented
@vadimzhukov ^

2022-12-09 16:01 UTC, nnslvp requested changes

2022-12-09 16:01 UTC, nnslvp commented on main.js
> +    document.getElementById('pool_hashrate').textContent = `${shortenHm(hashrate, 2).hashrate} ${shortenHm(hashrate, 2).units}/s`
Незачем два раза вызывать эту функцию

2022-12-09 16:01 UTC, nnslvp commented on stats.js
> +    document.getElementById('my_hashrate_24h_measure').textContent = shortenHm(day.hashrate, 2).units
Тут так же

2022-12-09 18:18 UTC, merged