feat: change ping indications
yahorbukhta/alephium-pool pull request #33
Opened 2024-05-08 15:21 UTC by AndrewMatsiash

2024-05-08 15:21 UTC, AndrewMatsiash commented
<img width="1576" alt="Снимок экрана 2024-05-08 в 18 21 10" src="https://github.com/nnslvp/alephium-pool/assets/74107101/87e0e20b-6b5e-4e66-a2b0-d09e0fa15054">
<img width="669" alt="Снимок экрана 2024-05-08 в 18 21 20" src="https://github.com/nnslvp/alephium-pool/assets/74107101/6c954a1d-ddc8-4fd8-a651-71b4d7f4a322">

2024-05-09 15:21 UTC, nnslvp commented on index.html
> -    <script>(function (w, d, s, l, i) {
не делай лишних измененйи плз

2024-05-09 15:22 UTC, nnslvp commented on main.js
> +      message = `😎 Отлично (низкий пинг до 50 мс)`;
нужно выводить просто смайлики

2024-05-09 15:26 UTC, nnslvp commented
> <img alt="Снимок экрана 2024-05-08 в 18 21 10" width="1576" src="https://private-user-images.githubusercontent.com/74107101/328945861-87e0e20b-6b5e-4e66-a2b0-d09e0fa15054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjg1MzksIm5iZiI6MTcxNTI2ODIzOSwicGF0aCI6Ii83NDEwNzEwMS8zMjg5NDU4NjEtODdlMGUyMGItNmI1ZS00ZTY2LWEyYjAtZDA5ZTBmYTE1MDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE1MjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYTU3OGM0OWI5YmVmY2JhY2QwNzg3ZWMwM2U4ZjQzYWEwNGVjOWVlNDdjMDk4YWMyYWNjYThkYzc5ZDQzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.avD11SdZdhHpL8Tpq-RsycMgtr353E4L2vx5nYhMQHk"> <img alt="Снимок экрана 2024-05-08 в 18 21 20" width="669" src="https://private-user-images.githubusercontent.com/74107101/328945873-6c954a1d-ddc8-4fd8-a651-71b4d7f4a322.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyNjg1MzksIm5iZiI6MTcxNTI2ODIzOSwicGF0aCI6Ii83NDEwNzEwMS8zMjg5NDU4NzMtNmM5NTRhMWQtZGRjOC00ZmQ4LWE2NTEtNzFiNGQ3ZjRhMzIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDE1MjM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhM2I3OTEyNmU3NWVjOTEwYjRhMDgxNjYyZTRlZDJhMzA2YjlkZjZjZGE3NTk2ZGMwMjllZTE3NGFiYTBmMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4xAllfLhpCpJWNReS1h0511dan7hVymZX6CFoMC5Ipk">

должны отображаться просто смайлы, я бы добавил ещк тултип, можно дефолтный типа “=< 50ms”, “=< 100” и так далее

2024-05-10 09:41 UTC, AndrewMatsiash commented on main.js
> +      message = `😎 Отлично (низкий пинг до 50 мс)`;
сделал 
<img width="942" alt="Снимок экрана 2024-05-10 в 12 39 37" src="https://github.com/nnslvp/alephium-pool/assets/74107101/dc87c9c3-dba8-46a9-9304-e4396e527d4c">
<img width="452" alt="Снимок экрана 2024-05-10 в 12 40 06" src="https://github.com/nnslvp/alephium-pool/assets/74107101/f75f83b4-fb32-4ee9-8ad0-e34bd31d786f">

2024-05-10 09:42 UTC, AndrewMatsiash commented on index.html
> -    <script>(function (w, d, s, l, i) {
🫡

2024-05-11 12:16 UTC, nnslvp commented on index.html
> -    <script>(function (w, d, s, l, i) {
лишние изменения на месте

2024-05-11 12:17 UTC, nnslvp commented on index.html
> +</html>
EOF

2024-05-13 15:29 UTC, AndrewMatsiash commented on index.html
> +</html>
сделал

2024-05-14 09:46 UTC, AndrewMatsiash commented on index.html
> -    <script>(function (w, d, s, l, i) {
убрал

2024-05-15 09:34 UTC, nnslvp requested changes

2024-05-15 09:34 UTC, nnslvp commented on index.html
> +                  <span class="tooltip"></span>
выравнивание

2024-05-15 09:34 UTC, nnslvp commented on index.html
> +                <span class="tooltip"></span>
почему где-то span с тултипом стоит выше а где-то ниже?

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +    .then(() => {});
для чего эта пустая функция?

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +        tooltipText = '<= 50 ms';
тултип отличается от условия

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +      if (pingValue < 50) {
```suggestion
      if (pingValue <= 50) {
```

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +      } else if (pingValue >= 50 && pingValue < 100) {
```suggestion
      } else if (pingValue <= 100) {
```

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +        tooltipText = '50-99 ms';
```suggestion
        tooltipText = '50-100 ms';
```

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +      } else if (pingValue >= 100 && pingValue < 200) {
```suggestion
      } else if (pingValue <= 200) {
```

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +        tooltipText = '100-199 ms';
```suggestion
        tooltipText = '100-200 ms';
```

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +      } else if (pingValue >= 200) {
```suggestion
      } else {
```

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +        tooltipText = '≥ 200 ms';
```suggestion
        tooltipText = '> 200 ms';
```

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +    }
тут четыре пробела

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +      pingCell.classList.add('fade-in-animation');
тут два пробела

2024-05-15 09:34 UTC, nnslvp commented on instruction.js
> +    }
так должно быть?

2024-05-15 09:45 UTC, AndrewMatsiash commented on index.html
> +                  <span class="tooltip"></span>
сделал

2024-05-15 09:45 UTC, AndrewMatsiash commented on index.html
> +                <span class="tooltip"></span>
это ни как не сказывается на отображении, но я сделал ниже, как остальные

2024-05-15 09:46 UTC, AndrewMatsiash commented on instruction.js
> +    .then(() => {});
не нужна уже, убрал.

2024-05-15 09:47 UTC, AndrewMatsiash commented on instruction.js
> +        tooltipText = '<= 50 ms';
исправил

2024-05-15 09:47 UTC, AndrewMatsiash commented on instruction.js
> +      if (pingValue < 50) {
сделал

2024-05-15 09:47 UTC, AndrewMatsiash commented on instruction.js
> +        tooltipText = '100-199 ms';
исправил

2024-05-15 09:47 UTC, AndrewMatsiash commented on instruction.js
> +      } else if (pingValue >= 200) {
сделал

2024-05-15 09:47 UTC, AndrewMatsiash commented on instruction.js
> +        tooltipText = '≥ 200 ms';
исправил

2024-05-15 09:48 UTC, AndrewMatsiash commented on instruction.js
> +    }
нет, сделал два

2024-05-15 09:48 UTC, AndrewMatsiash commented on instruction.js
> +      pingCell.classList.add('fade-in-animation');
исправил

2024-05-15 09:56 UTC, nnslvp commented on instruction.js
> +        tooltipText = '50-99 ms';
@AndrewMatsiash пропустил

2024-05-15 09:56 UTC, nnslvp commented on instruction.js
> +    } else if (pingValue >= 100 && pingValue < 200) {
Пересмотри плз комменты к этому куску кода

2024-05-15 10:03 UTC, AndrewMatsiash commented on instruction.js
> +    } else if (pingValue >= 100 && pingValue < 200) {
![Снимок экрана 2024-05-15 в 13 02 28](https://github.com/nnslvp/alephium-pool/assets/74107101/d709918d-8507-41d8-b7e7-e3211aea7dec)
так? или я чего то не вижу

2024-05-15 10:07 UTC, nnslvp commented on instruction.js
> +    } else if (pingValue >= 100 && pingValue < 200) {
https://github.com/nnslvp/alephium-pool/pull/33#discussion_r1601300894
https://github.com/nnslvp/alephium-pool/pull/33#discussion_r1601301372
https://github.com/nnslvp/alephium-pool/pull/33#discussion_r1601300551

Если мой коммент не корректный то ответь плз почему, не пропускай комменты

2024-05-15 10:12 UTC, AndrewMatsiash commented on instruction.js
> +        tooltipText = '50-99 ms';
да, чет пропустил, сделал

2024-05-15 10:12 UTC, AndrewMatsiash commented on instruction.js
> +      } else if (pingValue >= 100 && pingValue < 200) {
сделал

2024-05-15 10:12 UTC, AndrewMatsiash commented on instruction.js
> +      } else if (pingValue >= 50 && pingValue < 100) {
сделал

2024-05-15 10:31 UTC, nnslvp approved these changes

2024-05-15 10:32 UTC, merged