Add calculator
yahorbukhta/alephium-pool pull request #6
Opened 2023-01-27 13:25 UTC by kup1dman

2023-01-27 17:25 UTC, nnslvp requested changes
Давай оставим только USD.

2023-01-27 17:25 UTC, nnslvp commented on index.html
> +                    <label for="hashrate_field">Hashrate</label>
```suggestion
                    <label for="hashrate_field">Hashrate (GH/s)</label>
```

2023-01-27 17:25 UTC, nnslvp commented on index.html
> +                    <label for="power_consumption_field">Power consumption</label>
```suggestion
                    <label for="power_consumption_field">Power consumption (W)</label>
```

2023-01-27 17:25 UTC, nnslvp commented on index.html
> +                    <label for="electricity_costs_field">Electricity costs</label>
```suggestion
                    <label for="electricity_costs_field">Electricity costs (USD/kWh)</label>
```

2023-01-27 17:25 UTC, nnslvp commented on index.html
> +                    <td><b>Last 1 hour</b></td>
```suggestion
                    <td><b>1 hour</b></td>
```

2023-01-27 17:25 UTC, nnslvp commented on index.html
> +                    <td><b>Last 24 hour</b></td>
```suggestion
                    <td><b>24 hour</b></td>
```

2023-01-27 17:25 UTC, nnslvp commented on index.html
> +                    <td><b>Last 7 days</b></td>
```suggestion
                    <td><b>7 days</b></td>
```

2023-01-27 17:30 UTC, nnslvp commented
Так же вынеси калькулятор на отдельную страницу плз

2023-01-27 17:44 UTC, nnslvp commented on index.html
> +                    <th>COSTS</th>
```suggestion
                    <th>ELECTRICITY COSTS</th>
```

?

2023-01-28 12:17 UTC, nnslvp commented on index.html
> +        <p><a href="/calculator.html"><b>Calculator</b></a></p>
```suggestion
        <p><a href="calculator.html"><b>Calculator</b></a></p>
```

2023-01-28 12:21 UTC, nnslvp commented
<img width="744" alt="image" src="https://user-images.githubusercontent.com/65916399/215266042-3f6ea5c5-f95c-43be-8521-2b9f45654b2f.png">

1) Hashrate предзаполни заначением: 1
2) Currency филд можно убрать
3) Electricity cost выравится за счет увиливания размеров филда
4) Делай подсчет таблицы при открытии страницы по предзаполненным данным

@kup1dman ^

2023-01-28 13:29 UTC, nnslvp requested changes

2023-01-28 13:29 UTC, nnslvp commented on calculator.js
> +    fetchPoolProfit().then(({profit}) => {
Для параллельных запросов можешь использовать Promise.all

2023-01-28 13:29 UTC, nnslvp commented on calculator.js
> +                reward = profit * hashrate_value;
Можем ли мы сделать parseFloat выше они раз для profit и rate? И не приходит ли эти значения уже в флоте?

2023-01-28 13:29 UTC, nnslvp commented on index.html
> +        <p><a href="/calculator.html"><b>Calculator</b></a></p>
@kup1dman ^

2023-01-28 17:44 UTC, nnslvp commented on calculator.html
> +                <tbody>
Я бы оставил таблицу пустой, а добавлял бы строки через js, это упростит код

2023-01-29 17:14 UTC, nnslvp requested changes

2023-01-29 17:14 UTC, nnslvp commented on calculator.js
> +    } else {
ты можешь распаковать аргументы

```suggestion
    Promise.all([fetchRate(), fetchPoolProfit()]).then([rate, profit]=> {
```

2023-01-29 17:18 UTC, kup1dman commented on calculator.js
> +    } else {
Я пробовал так, во первых оно подчеркивает красным, не хватает скобок, а во вторых оно почему то выдает NaN при такое распаковке

2023-01-29 18:18 UTC, nnslvp commented on calculator.js
> +    } else {
да, нужно ([rate, profit] => {}) ошибся.

2023-01-31 13:55 UTC, nnslvp requested changes

2023-01-31 13:55 UTC, nnslvp commented on calculator.js
> +    let tr_period = td.insertCell();
Use camelCase

2023-01-31 13:55 UTC, nnslvp commented on calculator.js
> +    tr.innerHTML = `${sign}` + ` ${parseFloat(value).toFixed(4)}` + ` ${currency_value}`
давай форматирование строки подними выше, тут оставим просто запись переданной строки

2023-01-31 22:12 UTC, merged